### ISSUE TITLE
Ground truth data for evaluation

### ISSUE THREAD

**Issue by acDante** [yale-nlp/DocMath-Eval#3]
Hi, I am trying to run the evaluation script `evaluation.py` to evaluate my prediction results on DocMath-Eval test sets. However, I got the following issue: 

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/simplong_testmini.json'
```

What is the expected format of the ground truth raw data? Should I save the datasets downloaded from HF into json file and then put them at this directory?

**Comment by acDante** [comment]
Basically, I changed all the codes that load the ground truth data from a local file path into loading the DocMath-eval dataset from HF in the evaluation script. However, I evaluated the recall of different retrievers in the RAG model and found the performance much worse than the numbers reported in the paper.  Have you ever changed the dataset, or did I run the evaluation incorrectly?

**Comment by yilunzhao** [comment]
Hi @acDante, thanks for your interest in our work!

The ground truth features in the test set are hidden to prevent data contamination. Currently, you can send me the output in JSON format, and I’ll provide you with the test set results. We are trying to move the leaderboard and evaluation to Hugging Face, but that might take several weeks.

Regarding the RAG setting, we have released model outputs for both the retrieval stage and LLM generation stage (as detailed in the README). Could you please check those first?

**Comment by acDante** [comment]
Thanks! I will also check the output you provided. I am using the `complong_testmini` set and evaluating the retriever performance by comparing the retriever output against the annotation of table_evidence and paragraph_evidence provided in this test dataset. However, the recall is much lower than yours.

**Comment by acDante** [comment]
Is there a public complong validation set with the ground truth `table_evidence` and `paragraph_evidence` that I can use to evaluate my models locally?

**Comment by yilunzhao** [comment]
>  Is there a public complong validation set with the ground truth table_evidence and paragraph_evidence that I can use to evaluate my models locally?

If you're referring to the public complong **testmini set**, it is already available on Hugging Face. You can find the corresponding JSON files (so that you can directly download locally) at: [Hugging Face Dataset](https://huggingface.co/datasets/yale-nlp/DocMath-Eval/tree/c0177f0b03c28404fa70d2354e12d269258eac73/data).

I would recommend first comparing your retriever's output with ours to check for any implementation errors. One thing to note is that the Hugging Face dataset doesn't allow us to use an empty list for a feature value, so when a list is empty, we use [-1] as a placeholder. During evaluation, you should remove all the "-1" indices.

**Comment by acDante** [comment]
Thanks very much! The issue is exactly caused by the placeholder indices. After removing the -1 indices from the ground truth, I am able to get similar numbers as yours.
